name: all-devices
description: All devices stream.
super_stream: null
path_imu:
  dir: "${path.openpack.rootdir}/${user.name}/atr/${device}"
  fname: "${session}.csv"
frame_rate_imu: 30
devices:
  - 'atr01'
  - 'atr02'
acc: True
gyro: True
quat: False
imu_dim: 12
min_value_imu_acc: -4
max_value_imu_acc: 4
min_value_imu_gyro: -2000
max_value_imu_gyro: 2000

path_keypoint: 
  dir: "${path.openpack.rootdir}/${user.name}/kinect/${..category}/${..model}/single"
  fname: "${session}.json"
frame_rate_keypoint: 15
category: "2d-kpt"
model: "mmpose-hrnet-w48-posetrack18-384x288-posewarper-stage2"
nodes: {
    0: "nose",
    1: "left_eye",
    2: "right_eye",
    3: "left_ear",
    4: "right_ear",
    5: "left_shoulder",
    6: "right_shoulder",
    7: "left_elbow",
    8: "right_elbow",
    9: "left_wrist",
    10: "right_wrist",
    11: "left_hip",
    12: "right_hip",
    13: "left_knee",
    14: "right_knee",
    15: "left_ankle",
    16: "right_ankle",
}
keypoint_dim: 34
min_value_keypoint: 0
max_value_keypoint: 1280

path_e4:
  dir: "${path.openpack.rootdir}/${user.name}/e4/${device}/acc"
  fname: "${session}.csv"
frame_rate_e4: 32
devices_e4:
  - 'e401'
  - 'e402'